name: auramed
description: A new Flutter project.



publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'







dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.2.1
  url_launcher: ^6.1.6
  badges:
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true
  assets:
    - assets/
    - assets/qr_code/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
